title = "Aniruddha Mukherjee"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Champaign, IL"
email = "am31@illinois.edu"
favicon = "/favicon.ico"
firstName = "Aniruddha"
lastName = "Mukherjee"
#phone = "1-555-555-1234"
profileImage = "img/profile_pic.png"
showEducation = true
showExperience = false
showOpenSource = false
showProjects = true
showPublications = false
showQr = false
showSkills = false

#[params.google]

#[params.google.analytics]
#trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/aniruddha-mukherjee-636a451a3/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/aniruddha121500/"
name = "GitHub"

[[params.handles]]
link = "https://aniruddhamukherjeesite.wordpress.com"
name = "Wordpress"


#[[params.handles]]
#link = "https://stackoverflow.com/users/story/82880"
#name = "Stack Overflow"

#[[params.handles]]
#link = "https://keybase.io/edwardawebb"
#name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

#[taxonomies]
#tag = "tags"
